browser: Send files in binary
Files -- such as the compass rose for `pebble emu-control` -- were opened in
platform encoding (the default for `open()`), and then encoded to UTF-8
(the default for `str.encode()`).

For ASCII files this mostly works, since most encodings are ASCII-compatible.
For UTF-8 files it would show garbled characters if the platform encoding isn't
UTF-8 (i.e. Windows).
But it breaks on binary files, such as the compass rose, with:
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

Instead of auto-decoding to and re-encoding to bytes, open the file in binary
mode (`rb`), and send the bytes.